#!/bin/sh
#
# @name VTOL Tiltrotor
#
# @type VTOL Tiltrotor
#

. ${R}etc/init.d/rc.vtol_defaults
. ${R}etc/init.d/rc.ctrlalloc

param set-default MPC_USE_HTE 0
param set-default VM_MASS 1.5
param set-default MPC_THR_HOVER 0.5

param set-default FW_L1_PERIOD 12
#param set-default FW_AIRSPD_MAX 60
#param set-default FW_AIRSPD_MIN 14
#param set-default FW_AIRSPD_TRIM 20

param set-default FW_MAN_P_MAX 30
param set-default FW_PR_FF 0.2
param set-default FW_PR_I 0.4
param set-default FW_PR_P 0.15
param set-default FW_YR_FF 8.3
param set-default FW_YR_I 0.5
param set-default FW_YR_P 0.2
param set-default FW_PSP_OFF 2
param set-default FW_P_LIM_MAX 32
param set-default FW_P_LIM_MIN -15
param set-default FW_R_LIM 40
param set-default FW_RR_FF 1.0
param set-default FW_RR_P 0.1
param set-default FW_RR_I 0.2
param set-default FW_THR_CRUISE 0.3
param set-default FW_THR_MAX 0.6
param set-default FW_THR_MIN 0.05
param set-default FW_T_ALT_TC 2
param set-default FW_T_CLMB_MAX 8
param set-default FW_T_HRATE_FF 0.5
param set-default FW_T_SINK_MAX 2.7
param set-default FW_T_SINK_MIN 2.2
param set-default FW_T_TAS_TC 2


param set-default MC_ROLLRATE_P 0.3
param set-default MC_YAW_P 1.6
param set-default MC_YAWRATE_P 1.0
param set-default MC_YAWRATE_k 5.0

param set-default MIS_TAKEOFF_ALT 10
#param set-default MIS_YAW_TMT 10
#param set-default MIS_LTRMIN_ALT 10

param set-default MPC_ACC_HOR_MAX 5
#param set-default MPC_THR_MIN 0.1
#param set-default MPC_TKO_SPEED 1
param set-default MPC_XY_P 0.8
param set-default MPC_XY_VEL_P_ACC 3
param set-default MPC_XY_VEL_I_ACC 4
param set-default MPC_XY_VEL_D_ACC 0.1
param set-default MPC_Z_VEL_MAX_DN 1.5
# motor failure to 0.3
param set AVC_Y_P 20.0
param set AVC_Y_K 2.0
param set AVC_X_P 20.0
param set AVC_X_K 2.0
param set AVC_Z_K 3.0
param set AVC_Z_P 20.0
param set AVC_Y_I 0.6
param set AVC_X_I 0.6
param set AVC_Z_I 0.05
# # motor failure to 0.5 MC
# param set AVC_Y_P 20.0
# param set AVC_Y_K 2.0
# param set AVC_X_P 20.0
# param set AVC_X_K 2.0
# param set AVC_Z_K 4.0
# param set AVC_Z_P 18.0
# param set AVC_Y_I 0.3
# param set AVC_X_I 0.3
# param set AVC_Z_I 0.05

#param set AVC_Y_D 0.45
#param set AVC_X_D 30.0
param set-default NAV_ACC_RAD 5
param set-default NAV_LOITER_RAD 80

param set VT_DWN_PITCH_MAX 30
param set VT_FWD_THRUST_EN 4
param set VT_FWD_THRUST_SC 0.7
#param set VT_FW_PERM_STAB 1
param set VT_ARSP_BLEND 8
param set VT_ARSP_TRANS 5
param set VT_PSHER_RMP_DT 4
#param set-default VT_F_TRANS_DUR 15
param set-default VT_F_TRANS_THR 0.75
#param set-default VT_ARSP_TRANS 20
param set-default VT_MOT_ID 1234
# param set-default VT_FW_MOT_OFFID 1234
param set-default VT_B_TRANS_DUR 8
param set-default VT_TILT_TRANS 0.6
param set-default VT_TILT_FW 1.0
param set-default VT_TYPE 1


param set-default CA_AIRFRAME 2
param set-default CA_METHOD 0
# rotors
param set-default CA_ACT0_MIN 0
param set-default CA_ACT1_MIN 0
param set-default CA_ACT2_MIN 0
param set-default CA_ACT3_MIN 0

param set-default CA_ACT0_MAX 1.0
param set-default CA_ACT1_MAX 1.0
param set-default CA_ACT2_MAX 1.0
param set-default CA_ACT3_MAX 1.0
# tilts
param set-default CA_ACT4_MIN -1.0
param set-default CA_ACT5_MIN -1.0
param set-default CA_ACT6_MIN -1.0
param set-default CA_ACT7_MIN -1.0

param set-default CA_ACT4_MAX 1.0
param set-default CA_ACT5_MAX 1.0
param set-default CA_ACT6_MAX 1.0
param set-default CA_ACT7_MAX 1.0
# ailerons
param set-default CA_ACT8_MIN -1.0
param set-default CA_ACT9_MIN -1.0
param set-default CA_ACT8_MAX 1.0
param set-default CA_ACT9_MAX 1.0
# elevator
param set-default CA_ACT10_MIN -1.0

param set-default CA_ACT10_MAX 1.0
# rudder
param set-default CA_ACT11_MIN -1.0

param set-default CA_ACT11_MAX 1.0

param set-default CA_MC_R0_PX 0.1515
param set-default CA_MC_R0_PY 0.245
param set-default CA_MC_R0_CT 6.5
param set-default CA_MC_R0_KM 0.05
param set-default CA_MC_R1_PX -0.1515
param set-default CA_MC_R1_PY -0.1875
param set-default CA_MC_R1_CT 6.5
param set-default CA_MC_R1_KM 0.05
param set-default CA_MC_R2_PX 0.1515
param set-default CA_MC_R2_PY -0.245
param set-default CA_MC_R2_CT 6.5
param set-default CA_MC_R2_KM -0.05
param set-default CA_MC_R3_PX -0.1515
param set-default CA_MC_R3_PY 0.1875
param set-default CA_MC_R3_CT 6.5
param set-default CA_MC_R3_KM -0.05


set MAV_TYPE 21

set MIXER_FILE etc/mixers-sitl/tiltrotor_sitl_direct.main.mix
set MIXER custom
